NEW_GAME_TEXT = "New Game"
SETTINGS_TEXT = "Settings"
EXIT_TEXT = "Exit"

BACK_TEXT = "Back"
SOUND_TEXT = "Sound:"
VSYNC_TEXT = "Vsync:"
ON_TEXT = "On"
OFF_TEXT = "Off"
FULLSCREEN_TEXT = "Fullscreen:"

ON1_OFFSET = 340
ON2_OFFSET = 320
ON3_OFFSET = 540

FONT = "font1.ttf"

VSYNC_MARGINS = 230
FULLSCREEN_MARGINS = 435